// utils/pythonGenerator.js
// Generates Python boilerplate based on GPIO planner assignments

const DEV_TTYAMA = { 0: 0, 2: 1, 3: 2, 4: 3, 5: 4 };

function uartPort(bcm) {
  const map = { 14: 0, 15: 0, 0: 2, 1: 2, 4: 3, 5: 3, 8: 4, 9: 4, 12: 5, 13: 5 };
  const uart = map[bcm] ?? 0;
  if (uart === 0) return "/dev/serial0";
  return `/dev/ttyAMA${DEV_TTYAMA[uart] ?? uart}`;
}

function spiDevice(bcm) {
  // SPI0 = /dev/spidev0.x, SPI1 = /dev/spidev1.x
  if ([10,9,11,8,7].includes(bcm)) return [0, bcm === 8 ? 0 : bcm === 7 ? 1 : 0];
  if ([20,19,21,16].includes(bcm)) return [1, 0];
  return [0, 0];
}

export function generatePythonCode(assignments, PINS) {
  const used = {
    i2c: false, spi: false, uart: new Set(),
    onewire: false, onewire_pin: 4,
    pwm: [], gpio_out: [], gpio_in: [],
    led: [], button: [], sensor: [],
    i2s: false, custom: [],
  };

  Object.entries(assignments).forEach(([pin, { fn, label }]) => {
    const p = PINS.find(x => x[0] === Number(pin));
    if (!p) return;
    const bcm = p[1];
    const f   = fn.toUpperCase();

    if (f.includes("I2C") || f.includes("SDA") || f.includes("SCL")) used.i2c = true;
    if (f.includes("SPI") || f.includes("MOSI") || f.includes("MISO") || f.includes("SCLK")) used.spi = true;
    if (f.includes("UART") || f.includes("TXD") || f.includes("RXD")) used.uart.add(bcm);
    if (f === "1-WIRE")     { used.onewire = true; used.onewire_pin = bcm ?? 4; }
    if (f === "PWM" || (f.includes("PWM") && !f.includes("SPI"))) used.pwm.push(bcm);
    if (f === "GPIO OUTPUT") used.gpio_out.push(bcm);
    if (f === "GPIO INPUT")  used.gpio_in.push(bcm);
    if (f === "LED")         used.led.push(bcm);
    if (f === "BUTTON")      used.button.push(bcm);
    if (f === "SENSOR")      used.sensor.push(bcm);
    if (f === "CUSTOM")      used.custom.push(bcm);
  });

  const blocks = [];

  // ── Header ──
  blocks.push(`#!/usr/bin/env python3
"""
GPIO setup generated by RPi4 GPIO Planner
Board: Raspberry Pi 4 Model B — BCM2711

Install dependencies:
  pip install RPi.GPIO gpiozero pigpio smbus2 spidev pyserial
  sudo pigpiod   # for hardware PWM
"""
`);

  // ── Imports ──
  const imports = ["import time"];
  if (used.gpio_out.length || used.gpio_in.length || used.led.length || used.button.length || used.pwm.length || used.sensor.length) {
    imports.push("import RPi.GPIO as GPIO");
  }
  if (used.led.length || used.button.length) {
    imports.push("from gpiozero import LED, Button, PWMLED");
  }
  if (used.pwm.length) imports.push("import pigpio");
  if (used.i2c) imports.push("import smbus2");
  if (used.spi) imports.push("import spidev");
  if (used.uart.size > 0) imports.push("import serial");
  if (used.onewire) imports.push("import glob");

  blocks.push(imports.join("\n"));

  // ── GPIO basic setup ──
  if (used.gpio_out.length || used.gpio_in.length || used.sensor.length) {
    const lines = [
      "\n# ── GPIO Setup ──────────────────────────────────────────",
      "GPIO.setmode(GPIO.BCM)",
      "GPIO.setwarnings(False)",
    ];
    used.gpio_out.forEach(bcm => lines.push(`GPIO.setup(${bcm}, GPIO.OUT)               # GPIO Output`));
    used.gpio_in.forEach(bcm  => lines.push(`GPIO.setup(${bcm}, GPIO.IN, pull_up_down=GPIO.PUD_UP)  # GPIO Input`));
    used.sensor.forEach(bcm   => lines.push(`GPIO.setup(${bcm}, GPIO.IN, pull_up_down=GPIO.PUD_UP)  # Sensor Input`));
    lines.push("\n# Cleanup on exit — always call this");
    lines.push("# GPIO.cleanup()");
    blocks.push(lines.join("\n"));
  }

  // ── LED (gpiozero) ──
  if (used.led.length) {
    const lines = ["\n# ── LEDs (gpiozero) ─────────────────────────────────────"];
    used.led.forEach((bcm, i) => {
      lines.push(`led${i > 0 ? i : ""} = LED(${bcm})`);
    });
    lines.push("");
    lines.push("# Usage:");
    used.led.forEach((bcm, i) => {
      const v = i > 0 ? `led${i}` : "led";
      lines.push(`# ${v}.on()      # turn on BCM${bcm}`);
      lines.push(`# ${v}.off()     # turn off`);
      lines.push(`# ${v}.toggle()  # toggle`);
      lines.push(`# ${v}.blink(on_time=0.5, off_time=0.5)`);
    });
    blocks.push(lines.join("\n"));
  }

  // ── Button (gpiozero) ──
  if (used.button.length) {
    const lines = ["\n# ── Buttons (gpiozero) ──────────────────────────────────"];
    used.button.forEach((bcm, i) => {
      const v = i > 0 ? `btn${i}` : "btn";
      lines.push(`${v} = Button(${bcm}, pull_up=True, bounce_time=0.05)`);
    });
    lines.push("");
    used.button.forEach((bcm, i) => {
      const v = i > 0 ? `btn${i}` : "btn";
      lines.push(`${v}.when_pressed  = lambda: print("BCM${bcm} pressed")`);
      lines.push(`${v}.when_released = lambda: print("BCM${bcm} released")`);
    });
    lines.push("# from signal import pause; pause()  # keep script running");
    blocks.push(lines.join("\n"));
  }

  // ── I2C ──
  if (used.i2c) {
    blocks.push(`
# ── I²C (smbus2) ─────────────────────────────────────────
# Bus 1 = header pins SDA=BCM2(Pin3) SCL=BCM3(Pin5)
bus = smbus2.SMBus(1)

# Scan all addresses (run once to discover devices):
def i2c_scan():
    found = []
    for addr in range(0x03, 0x78):
        try:
            bus.read_byte(addr)
            found.append(hex(addr))
        except OSError:
            pass
    print("I²C devices:", found)
    return found

# i2c_scan()

# Example — read a byte from device at address 0x68, register 0x75:
# val = bus.read_byte_data(0x68, 0x75)

# Example — write a byte:
# bus.write_byte_data(0x68, 0x6B, 0x00)

# bus.close()  # close when done`);
  }

  // ── SPI ──
  if (used.spi) {
    const [busNum] = spiDevice(0);
    blocks.push(`
# ── SPI (spidev) ─────────────────────────────────────────
spi = spidev.SpiDev()
spi.open(${busNum}, 0)            # bus=${busNum}, CE0
spi.max_speed_hz = 500_000
spi.mode = 0                # CPOL=0 CPHA=0 (most common)

# Full-duplex transfer — tx and rx same length:
# rx = spi.xfer2([0x00, 0x00])

# Example — MCP3008 ADC channel 0:
def read_adc(channel):
    assert 0 <= channel <= 7
    r = spi.xfer2([1, (8 + channel) << 4, 0])
    return ((r[1] & 3) << 8) + r[2]

# voltage = read_adc(0) * 3.3 / 1023

# spi.close()`);
  }

  // ── UART ──
  if (used.uart.size > 0) {
    const bcms    = [...used.uart];
    const portStr = uartPort(bcms[0]);
    blocks.push(`
# ── UART (pyserial) ──────────────────────────────────────
# Disable serial console first:
#   sudo raspi-config → Interface Options → Serial Port
#   Login shell: No   |   Hardware port: Yes

ser = serial.Serial(
    port="${portStr}",
    baudrate=115200,
    bytesize=serial.EIGHTBITS,
    parity=serial.PARITY_NONE,
    stopbits=serial.STOPBITS_ONE,
    timeout=1
)

# Send:
# ser.write(b"Hello\\n")

# Receive a line:
# line = ser.readline().decode("utf-8", errors="ignore").strip()

# Non-blocking loop:
# while True:
#     if ser.in_waiting:
#         print(ser.readline().decode("utf-8", errors="ignore").strip())
#     time.sleep(0.01)

# ser.close()`);
  }

  // ── Hardware PWM ──
  if (used.pwm.length) {
    const pin = used.pwm[0];
    blocks.push(`
# ── Hardware PWM (pigpio) ─────────────────────────────────
# Start daemon first: sudo pigpiod
pi = pigpio.pi()

# BCM${pin} — hardware PWM
# Frequency 50Hz (servo), duty 0–1000000 (0–100%)
pi.hardware_PWM(${pin}, 50, 75_000)   # 7.5% = 90° servo neutral

# Servo positions:
# pi.hardware_PWM(${pin}, 50, 50_000)   # 0°   (1.0 ms)
# pi.hardware_PWM(${pin}, 50, 75_000)   # 90°  (1.5 ms)
# pi.hardware_PWM(${pin}, 50, 100_000)  # 180° (2.0 ms)

# LED PWM at 1kHz:
# pi.hardware_PWM(${pin}, 1000, 500_000)  # 50% brightness

# pi.hardware_PWM(${pin}, 0, 0)  # off
# pi.stop()`);
  }

  // ── 1-Wire ──
  if (used.onewire) {
    blocks.push(`
# ── 1-Wire DS18B20 (BCM${used.onewire_pin}) ───────────────────────────────
# Requires: dtoverlay=w1-gpio,gpiopin=${used.onewire_pin} in /boot/config.txt
# Add 4.7kΩ pull-up between DATA and 3.3V

def read_ds18b20(sensor_path):
    """Read temperature from a DS18B20 sensor."""
    with open(f"{sensor_path}/w1_slave") as f:
        lines = f.readlines()
    if "YES" in lines[0]:
        raw = lines[1].split("t=")[1].strip()
        celsius = float(raw) / 1000.0
        return celsius, celsius * 9/5 + 32
    return None, None

# Discover all sensors:
sensors = glob.glob("/sys/bus/w1/devices/28-*")
print(f"Found {len(sensors)} DS18B20 sensor(s)")

for sensor_path in sensors:
    sensor_id = sensor_path.split("/")[-1]
    c, f = read_ds18b20(sensor_path)
    if c is not None:
        print(f"  {sensor_id}: {c:.3f}°C / {f:.1f}°F")

# Continuous polling:
# while True:
#     for s in sensors:
#         c, f = read_ds18b20(s)
#         print(f"{s.split('/')[-1]}: {c:.2f}°C")
#     time.sleep(1)`);
  }

  // ── Custom ──
  if (used.custom.length) {
    blocks.push(`
# ── Custom pins ──────────────────────────────────────────
# BCM pins marked Custom: ${used.custom.join(", ")}
# Configure these manually based on your hardware`);
  }

  // ── Main guard ──
  blocks.push(`
# ── Main ─────────────────────────────────────────────────
if __name__ == "__main__":
    print("GPIO configured. Starting...")
    try:
        while True:
            # Your main loop here
            time.sleep(0.1)
    except KeyboardInterrupt:
        print("\\nStopped.")
    finally:
        # Cleanup
        ${used.gpio_out.length || used.gpio_in.length ? "GPIO.cleanup()" : "pass"}
        ${used.uart.size > 0 ? "ser.close()" : ""}
        ${used.spi ? "spi.close()" : ""}
        ${used.i2c ? "bus.close()" : ""}
        ${used.pwm.length ? "pi.stop()" : ""}
`);

  return blocks.join("\n");
}

// ── Setup.sh generator ────────────────────────────────────────────────────────
export function generateSetupSh(assignments, PINS) {
  const used = { i2c: false, spi: false, uart: false, onewire: false, pwm: false, cam: false };

  Object.entries(assignments).forEach(([, { fn }]) => {
    const f = fn.toUpperCase();
    if (f.includes("I2C") || f.includes("SDA") || f.includes("SCL")) used.i2c = true;
    if (f.includes("SPI") || f.includes("MOSI")) used.spi = true;
    if (f.includes("UART") || f.includes("TXD")) used.uart = true;
    if (f === "1-WIRE")  used.onewire = true;
    if (f.includes("PWM")) used.pwm = true;
  });

  const lines = [
    "#!/bin/bash",
    "# setup.sh — generated by RPi4 GPIO Planner",
    "# Run with: bash setup.sh",
    "",
    'echo "🍓 RPi4 GPIO Setup Script"',
    "",
    "# ── Enable interfaces via raspi-config ──────────────────",
  ];

  if (used.i2c) {
    lines.push('echo "Enabling I2C..."');
    lines.push("sudo raspi-config nonint do_i2c 0");
    lines.push("sudo apt-get install -y i2c-tools");
  }
  if (used.spi) {
    lines.push('echo "Enabling SPI..."');
    lines.push("sudo raspi-config nonint do_spi 0");
  }
  if (used.uart) {
    lines.push('echo "Enabling UART..."');
    lines.push("sudo raspi-config nonint do_serial_hw 0");
    lines.push("sudo raspi-config nonint do_serial_cons 1");
  }
  if (used.onewire) {
    lines.push('echo "Enabling 1-Wire..."');
    lines.push("sudo raspi-config nonint do_onewire 0");
  }

  lines.push("");
  lines.push("# ── Install Python packages ─────────────────────────────");
  lines.push("pip3 install --break-system-packages \\");

  const pkgs = ["RPi.GPIO", "gpiozero"];
  if (used.i2c) pkgs.push("smbus2");
  if (used.spi) pkgs.push("spidev");
  if (used.uart) pkgs.push("pyserial");
  if (used.pwm) pkgs.push("pigpio");

  pkgs.forEach((p, i) => lines.push(`  ${p}${i < pkgs.length - 1 ? " \\" : ""}`));

  if (used.pwm) {
    lines.push("");
    lines.push("# ── Start pigpio daemon ─────────────────────────────────");
    lines.push("sudo systemctl enable pigpiod");
    lines.push("sudo systemctl start pigpiod");
  }

  lines.push("");
  lines.push('echo "✅ Setup complete! Reboot recommended: sudo reboot"');

  return lines.join("\n");
}